name: CI

on:
  pull_request:
    branches: [ '*' ]
  push:
    branches: [ 'master' ]
    tags: [ '*' ]

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.18
      - name: Run Tests
        run: make test
