name: Publish SBOM

on:
  push:
    tags:
      # Releases
      - '[0-9]+.[0-9]+.[0-9]+'

# Permissions should look like this
permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  create-sbom-release-asset:
    name: Create SBOM Release Asset
    runs-on: ubuntu-latest
    steps:
      # If you don't check the code out, the SBOM will be empty
      - uses: actions/checkout@v4
      - name: Publish SBOM to Release Assets
        uses: anchore/sbom-action@v0
        with:
          path: ./  # actions/checkout default location
          format: cyclonedx-json
